Complete scrolling challenge and make popup for project view
gnuion/microverse_portfolio pull request #11
Opened 2022-07-19 10:40 UTC by gnuion

In this pull request we:
- Complete the scrolling challenge
- Inject HTML using JavaScript

2022-07-19 20:53 UTC, cynthiainga reviewed
Hi @gnuion, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that has the linters errors. Linter result should be green, this means that the last commit has a green check mark (✅)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-20 09:51 UTC, youmari requested changes
Hi @gnuion , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great title and short summary 
✔️ No linter error
✔️ Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 09:51 UTC, youmari commented on data.js
> +export default projects;
- [ ] please It would be better to keep only the one that generated dynamically with javascript and delete the other ones in the `index.html`

2022-07-20 09:51 UTC, youmari commented on src/components/buttons.js
> +  ];
- [ ] please make sure to stick to the Figma design and try to make the same buttons in order to match it 
![image](https://user-images.githubusercontent.com/61790587/179953243-739c74f5-fd56-434c-9d0b-2096c14f224c.png)

2022-07-20 10:36 UTC, gnuion commented on src/components/buttons.js
> +  ];
There icons are just placeholders, the challenge for this exercise was focused on generating the popup dynamically.

2022-07-20 12:16 UTC, Lameck1 reviewed
Hello, @gnuion 👋,

_This is an additional review as a result of the second opinion request._

Apologies for any misunderstanding that might have occurred in the last review of this PR. The hard part of this is that we are dealing with the project's requirements which have to be adhered to.

I would like to confirm the review is properly in line with all guidelines and that I have attempted to provide a proper explanation of what needs to be done in the inline comments below.

Please work on the required changes and then ask for another review.

Keep rocking 🚀!

2022-07-20 12:16 UTC, Lameck1 commented on src/components/buttons.js
> +  ];
- [ ] On the icons, they are not just a placeholder. They hold a meaning. Button Icons should be relevant to the functionality of the button.

  For example, the first button represents an external link to the live project, not to a youtube channel or video. The second button is a link to the GitHub repository, not a Facebook page or profile. This is why we were provided with a design to follow so as to achieve a good UX if not the best.
  
  There are Fontawesome icons that are close enough to what's provided in the design. Please search for these on `fontawesome's` website:
  
  1. `arrow-up-right-from-square` - for the live version button.
  2. `github` - for the GitHub repository button.

  This is what the project requirement on this say:
  
  > - You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
  
  Just as was requested by the previous reviewer, please work on this too.

2022-07-20 12:26 UTC, gnuion commented on index.html
>          </article>
Okay, sorry, I did not understand the exercise.

2022-07-20 12:27 UTC, gnuion commented on src/components/buttons.js
> +  ];
Okay, thank you for the hint!

2022-07-20 12:47 UTC, gnuion commented on data.js
> +export default projects;
Okay, just done it without ejs

2022-07-20 12:52 UTC, muneebulrehman approved these changes
Hi @gnuion , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors
- Good follow-up with the previous reviewer.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 06:48 UTC, merged